/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/categorias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Categorias */
        get: operations["listar_categorias_categorias__get"];
        put?: never;
        /** Crear Categoria */
        post: operations["crear_categoria_categorias__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categorias/{categoria_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Categoria */
        get: operations["obtener_categoria_categorias__categoria_id__get"];
        put?: never;
        post?: never;
        /** Eliminar Categoria */
        delete: operations["eliminar_categoria_categorias__categoria_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Categoria */
        patch: operations["actualizar_categoria_categorias__categoria_id__patch"];
        trace?: never;
    };
    "/productos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Productos */
        get: operations["listar_productos_productos__get"];
        put?: never;
        /** Crear Producto */
        post: operations["crear_producto_productos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{producto_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Producto */
        get: operations["obtener_producto_productos__producto_id__get"];
        put?: never;
        post?: never;
        /** Eliminar Producto */
        delete: operations["eliminar_producto_productos__producto_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Producto */
        patch: operations["actualizar_producto_productos__producto_id__patch"];
        trace?: never;
    };
    "/productos/{producto_id}/imagen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subir Imagen */
        post: operations["subir_imagen_productos__producto_id__imagen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{producto_id}/variantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar Variante */
        post: operations["agregar_variante_productos__producto_id__variantes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/productos/{producto_id}/variantes/{variante_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar Variante */
        delete: operations["eliminar_variante_productos__producto_id__variantes__variante_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Stock De Variante */
        patch: operations["actualizar_stock_de_variante_productos__producto_id__variantes__variante_id__patch"];
        trace?: never;
    };
    "/carrito/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Carrito */
        post: operations["crear_carrito_carrito__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carrito/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Carrito */
        get: operations["obtener_carrito_carrito__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carrito/{session_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agregar Item */
        post: operations["agregar_item_carrito__session_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/carrito/{session_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Eliminar Item */
        delete: operations["eliminar_item_carrito__session_id__items__item_id__delete"];
        options?: never;
        head?: never;
        /** Actualizar Cantidad */
        patch: operations["actualizar_cantidad_carrito__session_id__items__item_id__patch"];
        trace?: never;
    };
    "/usuarios/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crear Usuario */
        post: operations["crear_usuario_usuarios__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Usuario Actual */
        get: operations["obtener_usuario_actual_usuarios_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/me/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Mis Pedidos */
        get: operations["listar_mis_pedidos_usuarios_me_pedidos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_usuarios_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Pedidos */
        get: operations["listar_pedidos_pedidos__get"];
        put?: never;
        /** Crear Pedido */
        post: operations["crear_pedido_pedidos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Pedido */
        get: operations["obtener_pedido_pedidos__pedido_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pedidos/{pedido_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Estado */
        patch: operations["actualizar_estado_pedidos__pedido_id__estado_patch"];
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActualizarCantidadRequest */
        ActualizarCantidadRequest: {
            /** Cantidad */
            cantidad: number;
        };
        /** AgregarItemRequest */
        AgregarItemRequest: {
            /** Variante Id */
            variante_id: number;
            /** Cantidad */
            cantidad: number;
        };
        /** Body_subir_imagen_productos__producto_id__imagen_post */
        Body_subir_imagen_productos__producto_id__imagen_post: {
            /** Archivo */
            archivo: string;
        };
        /** CambiarEstadoRequest */
        CambiarEstadoRequest: {
            estado: components["schemas"]["EstadoPedido"];
        };
        /** CarritoCreado */
        CarritoCreado: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
        };
        /** CarritoItemResponse */
        CarritoItemResponse: {
            /** Id */
            id: number;
            producto: components["schemas"]["ProductoEnItem"];
            /** Variante Id */
            variante_id: number;
            /** Talla */
            talla: string;
            /** Cantidad */
            cantidad: number;
        };
        /** CarritoResponse */
        CarritoResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
            /** Items */
            items: components["schemas"]["CarritoItemResponse"][];
            /** Total */
            total: string;
        };
        /** CategoriaCreate */
        CategoriaCreate: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion?: string | null;
        };
        /** CategoriaResponse */
        CategoriaResponse: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion?: string | null;
            /** Id */
            id: number;
        };
        /** CategoriaUpdate */
        CategoriaUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Descripcion */
            descripcion?: string | null;
        };
        /**
         * EstadoPedido
         * @enum {string}
         */
        EstadoPedido: "pendiente" | "confirmado" | "en_preparacion" | "enviado" | "entregado" | "cancelado";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Pagina[CategoriaResponse] */
        Pagina_CategoriaResponse_: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["CategoriaResponse"][];
        };
        /** Pagina[PedidoResponse] */
        Pagina_PedidoResponse_: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["PedidoResponse"][];
        };
        /** Pagina[ProductoResponse] */
        Pagina_ProductoResponse_: {
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["ProductoResponse"][];
        };
        /** PedidoCreate */
        PedidoCreate: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Nombre Contacto */
            nombre_contacto: string;
            /**
             * Email Contacto
             * Format: email
             */
            email_contacto: string;
            /** Telefono Contacto */
            telefono_contacto: string;
            /** Direccion Envio */
            direccion_envio: string;
        };
        /** PedidoItemResponse */
        PedidoItemResponse: {
            /** Id */
            id: number;
            producto: components["schemas"]["ProductoEnPedido"];
            /** Talla */
            talla: string;
            /** Cantidad */
            cantidad: number;
            /** Precio Unitario */
            precio_unitario: string;
        };
        /** PedidoResponse */
        PedidoResponse: {
            /** Id */
            id: number;
            estado: components["schemas"]["EstadoPedido"];
            /** Nombre Contacto */
            nombre_contacto: string;
            /**
             * Email Contacto
             * Format: email
             */
            email_contacto: string;
            /** Telefono Contacto */
            telefono_contacto: string;
            /** Direccion Envio */
            direccion_envio: string;
            /** Total */
            total: string;
            /**
             * Fecha Creacion
             * Format: date-time
             */
            fecha_creacion: string;
            /** Items */
            items: components["schemas"]["PedidoItemResponse"][];
        };
        /** ProductoCreate */
        ProductoCreate: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion?: string | null;
            /** Precio */
            precio: number | string;
            /** Categoria Id */
            categoria_id: number;
            /** Imagen */
            imagen?: string | null;
            /**
             * Variantes
             * @default []
             */
            variantes: components["schemas"]["VarianteCreate"][];
        };
        /** ProductoEnItem */
        ProductoEnItem: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Precio */
            precio: string;
            /** Imagen */
            imagen: string | null;
        };
        /** ProductoEnPedido */
        ProductoEnPedido: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Imagen */
            imagen: string | null;
        };
        /** ProductoResponse */
        ProductoResponse: {
            /** Nombre */
            nombre: string;
            /** Descripcion */
            descripcion?: string | null;
            /** Precio */
            precio: string;
            /** Categoria Id */
            categoria_id: number;
            /** Imagen */
            imagen?: string | null;
            /** Id */
            id: number;
            categoria: components["schemas"]["CategoriaResponse"];
            /** Variantes */
            variantes: components["schemas"]["VarianteResponse"][];
        };
        /** ProductoUpdate */
        ProductoUpdate: {
            /** Nombre */
            nombre?: string | null;
            /** Descripcion */
            descripcion?: string | null;
            /** Precio */
            precio?: number | string | null;
            /** Categoria Id */
            categoria_id?: number | null;
            /** Imagen */
            imagen?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UsuarioCreate */
        UsuarioCreate: {
            /** Nombre */
            nombre: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UsuarioLogin */
        UsuarioLogin: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** UsuarioResponse */
        UsuarioResponse: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Es Admin */
            es_admin: boolean;
            /**
             * Fecha Registro
             * Format: date-time
             */
            fecha_registro: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VarianteCreate */
        VarianteCreate: {
            /** Talla */
            talla: string;
            /**
             * Stock
             * @default 0
             */
            stock: number;
        };
        /** VarianteResponse */
        VarianteResponse: {
            /** Id */
            id: number;
            /** Talla */
            talla: string;
            /** Stock */
            stock: number;
        };
        /** VarianteUpdate */
        VarianteUpdate: {
            /** Stock */
            stock: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_categorias_categorias__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_CategoriaResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_categoria_categorias__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_categoria_categorias__categoria_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoria_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_categoria_categorias__categoria_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoria_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_categoria_categorias__categoria_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                categoria_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoriaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_productos_productos__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                categoria_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ProductoResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_producto_productos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_producto_productos__producto_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_producto_productos__producto_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_producto_productos__producto_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    subir_imagen_productos__producto_id__imagen_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_subir_imagen_productos__producto_id__imagen_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agregar_variante_productos__producto_id__variantes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VarianteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VarianteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_variante_productos__producto_id__variantes__variante_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
                variante_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_stock_de_variante_productos__producto_id__variantes__variante_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                producto_id: number;
                variante_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VarianteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VarianteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_carrito_carrito__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarritoCreado"];
                };
            };
        };
    };
    obtener_carrito_carrito__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarritoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agregar_item_carrito__session_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarritoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eliminar_item_carrito__session_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_cantidad_carrito__session_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarCantidadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CarritoItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_usuario_usuarios__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_usuario_actual_usuarios_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioResponse"];
                };
            };
        };
    };
    listar_mis_pedidos_usuarios_me_pedidos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_PedidoResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_usuarios_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UsuarioLogin"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_pedidos_pedidos__get: {
        parameters: {
            query?: {
                estado?: components["schemas"]["EstadoPedido"] | null;
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_PedidoResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_pedido_pedidos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PedidoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_pedido_pedidos__pedido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_estado_pedidos__pedido_id__estado_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedido_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarEstadoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PedidoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
